---
title: "R Practice: Tidy Data and Joins"
format: html
---

## Setup
```{r}
library(readr)
library(dplyr)
library(tidyr)
library(lubridate) # for bonus question
# Quick question: Do you get a message after loading the libraries? What is it telling you? Talk to your neighbor about it or write a note in your qmd.

# We do get an error message stating that several functions in base r are masked by lubridate
```

## Bring in data and check out
```{r}
bird_observations <- read_csv("https://portal.edirepository.org/nis/dataviewer?packageid=knb-lter-cap.256.10&entityid=53edaa7a0e083013d9bf20322db1780e")

glimpse(bird_observations)
summary(bird_observations)

sites <- read_csv("https://portal.edirepository.org/nis/dataviewer?packageid=knb-lter-cap.256.10&entityid=81bf72420e69077097fb0790dcdc63a6")

glimpse(sites)
summary(sites)

surveys <- read_csv("https://portal.edirepository.org/nis/dataviewer?packageid=knb-lter-cap.256.10&entityid=b2466fa5cb5ed7ee1ea91398fc291c59")

glimpse(surveys)
summary(surveys)

taxalist <- read_csv("https://portal.edirepository.org/nis/dataviewer?packageid=knb-lter-cap.256.10&entityid=58f863b7e3066e68536a9cacdc7bd58e")

glimpse(taxalist)
summary(taxalist)

```




